package:
  name: py_gnome
  version: 0.1.1

# no source -- source is local

requirements:
  build:
    - python
    - setuptools
    - numpy
    - netcdf4
    - cython
  run:
    - oil_library
    - python
    - pytest
    - scipy
    - numpy
    - netcdf4
    - colander
    - pil
    - pyzmq
    - repoze.lru
    - six
    - geojson


about:
  home: https://github.com/NOAA-ORR-ERD/PyGnome
  license: Public Domain

