before_script: 
  - yum update -y
  - yum install gcc netcdf-devel
  - conda install --file conda_requirements.txt
  - cd ./py_gnome
  - pip install -r requirements.txt
  - python ./setup.py develop

master: 
  script:
    - py.test -runslow
  only: 
    - master

develop:
  script:
    - py.test
  only:
    - develop
