before_script: 
  - virtualenv gnomeenv --no-site-packages
  - source gnomeenv/bin/activate
  - cd ./py_gnome
  - pip install -r requirements.txt
  - python ./setup.py cleandev
  - python ./setup.py develop

master: 
  script:
    - py.test -runslow
  only: 
    - master

develop:
  script:
    - py.test
  only:
    - develop