before_script:
  - yum update -y
  - yum install gcc gcc-c++ -y
  - yum install netcdf-devel -y # needed by the C++ code -- it can't find the conda versions
  - yum install libXext libSM libXrender -y  # needed by matplotlib on CentOS

  # make sure the conda channels are set up right
  # the last channel you add will be first on the list
  - conda config --add channels defaults
  - conda config --add channels NOAA-ORR-ERD
  - conda config --add channels conda-forge

  # install the requirements
  - conda install --file conda_requirements.txt

  # get the oil libary package from gitlab
  - pip install -U git+https://srccontrol.orr.noaa.gov/gnome/OilLibrary.git@v0.0.9#egg=oil_library
  - cd ./py_gnome
  - python ./setup.py develop

master:
  script:
    - py.test -runslow
  only:
    - master

develop:
  script:
    - py.test
  only:
    - develop
