before_script: 
  - pip install -r ./py_gnome/requirements.txt
  - python ./py_gnome/setup.py cleandev
  - python ./py_gnome/setup.py develop

master: 
  script:
    - py.test -runslow
  only: 
    - master

develop:
  script:
    - py.test
 only:
   - develop