test:
  script:
  - yum update -y
  - yum install gcc gcc-c++ -y
  - yum install netcdf-devel -y # needed by the C++ code -- it can't find the conda versions
  - yum install libXext libSM libXrender -y  # needed by matplotlib on CentOS

  # make sure the conda channels are set up right
  # the last channel you add will be first on the list
  - conda config --add channels defaults
  - conda config --add channels NOAA-ORR-ERD
  - conda config --add channels conda-forge

  # install the requirements
  - conda install --file conda_requirements.txt

  - cd ./py_gnome
  - python ./setup.py install
  - py.test
  tags:
    - tests

develop:
  script:
    - docker build -f dockerfile . -t gitlab.orr.noaa.gov:5002/pygnome:develop
    - docker push gitlab.orr.noaa.gov:5002/pygnome:develop
  only:
    - develop
  tags:
    - docker

master:
  script:
    - docker build -f dockerfile . -t gitlab.orr.noaa.gov:5002/pygnome
    - docker push gitlab.orr.noaa.gov:5002/pygnome
  only:
     - master
  tags:
     - docker
